version: '3'
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - ./:/usr/src/app
    command: sh -c "cd react_app && npm start"
    ports:
      - "3000:3000"
